name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'area25-backend-main/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate deployment package
      run: |
        cd area25-backend-main/area25-backend-main
        zip -r ../../deploy.zip . -x "node_modules/*" ".git/*" "*.log" ".env" "*.zip"

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: area25-furniture-backend
        environment_name: area25-simple
        version_label: ${{ github.sha }}
        region: eu-north-1
        deployment_package: deploy.zip
        wait_for_environment_recovery: 300